# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'eventsDengun' do

  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

end
