
#platform :ios, '9.0'

use_frameworks!

target 'eventsDengun' do
#
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Storage', '~> 5.11.0'


  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

end
